package com.dd.company.batterychecker

const val PREF_NAME = "PREF_NAME"
const val ACTION_STOP_SERVER = "ACTION_STOP_SERVER"
const val KEY_PERCENT = "KEY_PERCENT"
const val KEY_TURN_ON_NOTIFY = "KEY_TURN_ON_NOTIFY"
const val KEY_ACTION_SERVICE = "KEY_ACTION_SERVICE"
const val ACTION_START_SERVICE = "ACTION_START_SERVICE"
const val ACTION_START_MUSIC = "ACTION_START_MUSIC"
const val ACTION_STOP_MUSIC = "ACTION_STOP_MUSIC"